### ISSUE TITLE
exec user process caused: exec format error

### ISSUE THREAD

**Issue by jinminhao** [csantanapr/knative-pi#3]
I tried to install knative serving on Raspberry Pi 4B and it seems that all the images in `serving-core.yaml` are compiled for AMD64, not ARM64. The pods will return error `exec user process caused: exec format error` if I simply `kubectl apply` these yaml. Do you have any idea on how to solve it? Thx in advance!

**Comment by xtreme-sameer-vohra** [comment]
Which version of Knative are you using @jinminhao ?
I was able to install Knative Serving v0.25.0 without issues on a Raspberry Pi with Ubuntu 64bit.
Looking at the activator image
```
crane manifest gcr.io/knative-releases/knative.dev/serving/cmd/activator@sha256:f1e3e516a26ec07fbbbcefcce7619c74dd3b9ee943a5041a7f35c3f848964c0c | jq .
```
There are arm and arm64 images.

**Comment by jinminhao** [comment]
Ah thanks! I will have a try later.
